Traceback (most recent call last):
  File "/hpc/home/etb28/coganlab/etb28/GlobalLocal/dcc_scripts/spec/plot_wavelets_dcc.py", line 57, in <module>
    main(args.subject)
  File "/hpc/home/etb28/coganlab/etb28/GlobalLocal/dcc_scripts/spec/plot_wavelets_dcc.py", line 31, in main
    spec = load_wavelets(subject_id, layout, output_name, rescaled)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/etb28/coganlab/etb28/GlobalLocal/src/analysis/spec/wavelet_functions.py", line 464, in load_wavelets
    spec = load_tfrs(filename)
           ^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/etb28/coganlab/etb28/GlobalLocal/src/analysis/spec/wavelet_functions.py", line 391, in load_tfrs
    tfr_result = mne.time_frequency.read_tfrs(filename)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-177>", line 12, in read_tfrs
  File "/hpc/home/etb28/miniconda3/envs/ieeg/lib/python3.11/site-packages/mne/time_frequency/tfr.py", line 4163, in read_tfrs
    hdf5_dict = read_hdf5(fname, title="mnepython", slash="replace")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/etb28/miniconda3/envs/ieeg/lib/python3.11/site-packages/h5io/_h5io.py", line 464, in read_hdf5
    raise IOError('file "%s" not found' % fname)
OSError: file "/cwork/etb28/BIDS-1.1_GlobalLocal/BIDS/derivatives/spec/wavelet/D0116/ErrorTrials_rescaled-tfr.h5" not found
