Traceback (most recent call last):
  File "/hpc/home/rl330/coganlab/rl330/GlobalLocal/src/analysis/pac/theta_connect.py", line 155, in <module>
    compute_and_plot_connectivity(
  File "/hpc/home/rl330/coganlab/rl330/GlobalLocal/src/analysis/pac/theta_connect.py", line 108, in compute_and_plot_connectivity
    raise AttributeError(f"Could not find time coordinate in connectivity object. Available coords: {list(con.coords)}")
AttributeError: Could not find time coordinate in connectivity object. Available coords: ['epochs', 'node_in -> node_out', 'freqs']
