Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
/hpc/home/jz421/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:422: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs)
/hpc/home/jz421/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:422: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs)
/hpc/home/jz421/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:422: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs)
/hpc/home/jz421/coganlab/jz421/GlobalLocal/src/analysis/utils/general_utils.py:422: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  event_epochs = mne.concatenate_epochs(combined_epochs)
Traceback (most recent call last):
  File "/hpc/home/jz421/coganlab/jz421/GlobalLocal/dcc_scripts/decoding/run_decoding_dcc.py", line 185, in run_analysis
    main(args)
  File "/hpc/home/jz421/coganlab/jz421/GlobalLocal/dcc_scripts/decoding/decoding_dcc.py", line 280, in main
    significant_clusters, p_values = time_perm_cluster(
                                     ^^^^^^^^^^^^^^^^^^
  File "/hpc/home/jz421/miniconda3/envs/ieeg/lib/python3.11/site-packages/ieeg/calc/stats.py", line 471, in time_perm_cluster
    if isinstance(stat_func(np.array([1]), np.array([1]), axis), tuple):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/jz421/miniconda3/envs/ieeg/lib/python3.11/site-packages/scipy/stats/_axis_nan_policy.py", line 483, in axis_nan_policy_wrapper
    samples = _broadcast_arrays(samples, axis=axis)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/jz421/miniconda3/envs/ieeg/lib/python3.11/site-packages/scipy/stats/_axis_nan_policy.py", line 18, in _broadcast_arrays
    new_shapes = _broadcast_array_shapes(arrays, axis=axis)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/jz421/miniconda3/envs/ieeg/lib/python3.11/site-packages/scipy/stats/_axis_nan_policy.py", line 30, in _broadcast_array_shapes
    return _broadcast_shapes(shapes, axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/jz421/miniconda3/envs/ieeg/lib/python3.11/site-packages/scipy/stats/_axis_nan_policy.py", line 62, in _broadcast_shapes
    raise AxisError(message)
numpy.exceptions.AxisError: `axis` is out of bounds for array of dimension 1
